## Importing the Packages

In [327]:
import numpy as np

In [328]:
np.set_printoptions(suppress=True, linewidth=100, precision=2)

## Importing the Data

In [329]:
raw_data_np=np.genfromtxt("loan-data.csv",
                          delimiter=';',
                          skip_header= 1)
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [330]:
raw_data_np.shape

(10000, 14)

## Checking for Incomplete Data

In [331]:
np.isnan(raw_data_np).sum()

88005

In [332]:
temporary_fill=np.nanmax(raw_data_np)+1
temporary_mean=np.nanmean(raw_data_np, axis=0)

C:\Users\KAUSTAV\AppData\Local\Temp\ipykernel_17548\2607916835.py:2: RuntimeWarning: Mean of empty slice
  temporary_mean=np.nanmean(raw_data_np, axis=0)


In [333]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [334]:
temporary_stat=np.array([np.nanmin(raw_data_np, axis=0),
                        temporary_mean,
                        np.nanmax(raw_data_np, axis=0)])

C:\Users\KAUSTAV\AppData\Local\Temp\ipykernel_17548\3494732836.py:1: RuntimeWarning: All-NaN slice encountered
  temporary_stat=np.array([np.nanmin(raw_data_np, axis=0),
C:\Users\KAUSTAV\AppData\Local\Temp\ipykernel_17548\3494732836.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_np, axis=0)])


In [335]:
temporary_stat

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

## Splitting the Dataset

### Splitting the Columns

In [336]:
column_strings=np.argwhere(np.isnan(temporary_mean)==True).squeeze()
column_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [337]:
column_numeric=np.argwhere(np.isnan(temporary_mean)==False).squeeze()
column_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

### Re-importing the Dataset

In [338]:
loan_data_strings=np.genfromtxt("loan-data.csv",
                               delimiter=';',
                               skip_header=1,
                               autostrip=True,
                               usecols=column_strings,
                               dtype=str)
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [339]:
loan_data_numeric=np.genfromtxt("loan-data.csv",
                               delimiter=';',
                               skip_header=1,
                               usecols=column_numeric,
                               autostrip=True,
                               filling_values=temporary_fill)
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

### The Names of the Columns

In [340]:
header_full=np.genfromtxt("loan-data.csv",
                          delimiter=';',
                          autostrip=True,
                          skip_footer=raw_data_np.shape[0],
                          dtype=str)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [341]:
header_strings, header_numeric=header_full[column_strings], header_full[column_numeric]

In [342]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [343]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

## Creating Checkpoints:

In [344]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [345]:
checkpoint_test=checkpoint("checkpoint_test", header_strings, loan_data_strings)

In [346]:
checkpoint_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [347]:
np.array_equal(checkpoint_test['data'], loan_data_strings)

True

## Manipulating String Columns

In [348]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [349]:
header_strings[0]='issue_date'

In [350]:
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

### Issue Date

In [351]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [352]:
loan_data_strings[:,0]=np.chararray.strip(loan_data_strings[:,0], "-15")

In [353]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [354]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [355]:
for i in range(13):
        loan_data_strings[:,0] = np.where(loan_data_strings[:,0] == months[i],
                                          i,
                                          loan_data_strings[:,0])

In [356]:
np.unique(loan_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Loan Status

In [357]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [358]:
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [359]:
bad_status=['', 'Charged Off', 'Default', 'Late (31-120 days)']

In [360]:
loan_data_strings[:,1]= np.where(np.isin(loan_data_strings[:,1], bad_status),0,1)

In [361]:
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

### Term

In [362]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [363]:
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [364]:
loan_data_strings[:,2]=np.chararray.strip(loan_data_strings[:,2], " months")

In [365]:
loan_data_strings[:,2]=np.where(loan_data_strings[:,2]=='', '60', loan_data_strings[:,2])

In [366]:
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

In [367]:
header_strings[2]='term_months'

In [368]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

### Grade and Subgrade

In [369]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [370]:
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [371]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

#### Filling Sub Grade

In [372]:
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') & (loan_data_strings[:,3] == i),
                                      i + '5',
                                      loan_data_strings[:,4])

In [373]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [374]:
loan_data_strings[:,4]=np.where(loan_data_strings[:,4]=='',
                                'H1',
                                loan_data_strings[:,4])

In [375]:
np.unique(loan_data_strings[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

#### Removing Grade

In [376]:
loan_data_strings=np.delete(loan_data_strings, 3, axis=1)

In [377]:
header_strings=np.delete(header_strings, 3)

In [378]:
loan_data_strings[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [379]:
header_strings[3]

'sub_grade'

#### Converting Sub Grade

In [380]:
np.unique(loan_data_strings[:,3]).size

36

In [381]:
keys = list(np.unique(loan_data_strings[:,3]))                         
values = list(range(1, np.unique(loan_data_strings[:,3]).shape[0] + 1)) 
dict_sub_grade = dict(zip(keys, values))

In [382]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [383]:
for i in np.unique(loan_data_strings[:,3]):
        loan_data_strings[:,3] = np.where(loan_data_strings[:,3] == i, 
                                          dict_sub_grade[i],
                                          loan_data_strings[:,3])

In [384]:
np.unique(loan_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Verification Status

In [385]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [386]:
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [387]:
loan_data_strings[:,4]=np.where((loan_data_strings[:,4]=='') | (loan_data_strings[:,4]=='Not Verified'),0,1)

In [388]:
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

### URL

In [389]:
loan_data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [390]:
loan_data_strings[:,5]=np.chararray.strip(loan_data_strings[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [391]:
loan_data_strings[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [392]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [393]:
loan_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [394]:
type(loan_data_numeric[0,0])

numpy.float64

In [395]:
np.array_equal(loan_data_numeric[:,0], loan_data_strings[:,5].astype(dtype=np.float64))

True

##### Therefore URL is a redundant column, Hence, we can can delete this

In [396]:
loan_data_strings=np.delete(loan_data_strings, 5, axis=1)

In [397]:
header_strings=np.delete(header_strings, 5)

In [398]:
loan_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [399]:
header_strings[5]

'addr_state'

### State Address

In [400]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [401]:
string_state_names, string_state_count=np.unique(loan_data_strings[:,5], return_counts=True)

In [402]:
sorted_state_count=np.argsort(-string_state_count)
string_state_names[sorted_state_count], string_state_count[sorted_state_count]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [403]:
loan_data_strings[:,5]=np.where(loan_data_strings[:,5]=='',
                                0,
                                loan_data_strings[:,5])

In [404]:
united_states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
united_states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
united_states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
united_states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf

In [405]:
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5], united_states_west), 1, loan_data_strings[:,5])
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5], united_states_south), 2, loan_data_strings[:,5])
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5], united_states_midwest), 3, loan_data_strings[:,5])
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5], united_states_east), 4, loan_data_strings[:,5])

In [406]:
np.unique(loan_data_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

## Converting to Numbers

In [407]:
loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [408]:
loan_data_strings=loan_data_strings.astype(dtype=np.int_)

In [409]:
loan_data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

### Checkpoint 1: Strings

In [410]:
checkpoint_strings=checkpoint("Checkpoint-Strings", header_strings, loan_data_strings)

In [411]:
np.array_equal(checkpoint_strings['header'], header_strings)

True

In [412]:
np.array_equal(checkpoint_strings['data'], loan_data_strings)

True

## Manipulating Numeric Columns

In [413]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [414]:
temporary_fill

68616520.0

In [415]:
np.isnan(loan_data_numeric).sum()

0

### Substitute "Filler" Values

In [416]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### ID

In [417]:
loan_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [418]:
np.isin(loan_data_numeric[:,0], temporary_fill)

array([False, False, False, ..., False, False, False])

In [419]:
np.isin(loan_data_numeric[:,0], temporary_fill).sum()

0

In [420]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### Temporary Stats

In [421]:
temporary_stat[:,column_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

#### Funded Amount

In [422]:
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == temporary_fill, 
                                  temporary_stat[0, column_numeric[2]],
                                  loan_data_numeric[:,2])
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [423]:
np.unique(loan_data_numeric[:,2])

array([ 1000.,  1100.,  1175.,  1200.,  1225.,  1325.,  1400.,  1450.,  1500.,  1600.,  1650.,
        1675.,  1725.,  1750.,  1800.,  1875.,  1900.,  1950.,  2000.,  2100.,  2200.,  2250.,
        2300.,  2350.,  2400.,  2500.,  2525.,  2600.,  2625.,  2650.,  2675.,  2700.,  2775.,
        2800.,  2875.,  2900.,  2950.,  3000.,  3050.,  3075.,  3100.,  3150.,  3200.,  3225.,
        3250.,  3275.,  3300.,  3325.,  3350.,  3400.,  3450.,  3475.,  3500.,  3525.,  3550.,
        3575.,  3600.,  3650.,  3700.,  3725.,  3750.,  3800.,  3850.,  3875.,  3900.,  3925.,
        3950.,  3975.,  4000.,  4025.,  4100.,  4125.,  4150.,  4175.,  4200.,  4225.,  4250.,
        4275.,  4300.,  4325.,  4350.,  4375.,  4400.,  4450.,  4475.,  4500.,  4525.,  4550.,
        4575.,  4600.,  4625.,  4650.,  4700.,  4725.,  4750.,  4800.,  4825.,  4875.,  4900.,
        4925.,  4950.,  4975.,  5000.,  5025.,  5050.,  5075.,  5100.,  5125.,  5150.,  5175.,
        5200.,  5225.,  5250.,  5275.,  5300.,  53

#### Loaned Amount, Interest Rate, Total Payment, Installment

In [424]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [425]:
for i in [1, 3, 4, 5]:
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i] == temporary_fill, 
                                      temporary_stat[2, column_numeric[i]],
                                      loan_data_numeric[:,i])

In [426]:
np.isin(loan_data_numeric, temporary_fill)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [427]:
np.isin(loan_data_numeric, temporary_fill).sum()

0

### Currency Change

#### The Exchange Rate

In [428]:
EUR_USD=np.genfromtxt("EUR-USD.csv",
                            delimiter=',',
                            autostrip=True,
                            skip_header=1,
                            usecols=3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [429]:
exchange_rate=loan_data_strings[:,0]

In [430]:
for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                             EUR_USD[i-1],
                             exchange_rate)    
exchange_rate = np.where(exchange_rate == 0,
                         np.mean(EUR_USD),
                         exchange_rate)

exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [431]:
exchange_rate.shape

(10000,)

In [432]:
exchange_rate=np.reshape(exchange_rate, (10000,1))

In [433]:
exchange_rate.shape

(10000, 1)

In [434]:
loan_data_numeric=np.hstack((loan_data_numeric, exchange_rate))

In [435]:
header_numeric=np.concatenate((header_numeric, np.array(["exchange_rate"])))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [436]:
loan_data_numeric.shape

(10000, 7)

#### From USD to EUR

In [437]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [438]:
column_dollars=np.array([1,2,4,5])

In [439]:
loan_data_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [440]:
for i in column_dollars:
    loan_data_numeric = np.hstack((loan_data_numeric, np.reshape((loan_data_numeric[:,i] / loan_data_numeric[:,6]), (10000,1))))

In [441]:
column_index_order= [0, 1, 7, 2, 8, 3, 4, 8, 5, 9, 6]

In [442]:
loan_data_numeric=loan_data_numeric[:,column_index_order]

In [443]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     1081.04,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,      848.86,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,      439.64,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1223.36,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,      318.78,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      283.49,        1.09]])

In [444]:
loan_data_numeric.shape

(10000, 11)

#### Expanding the header

In [445]:
header_additional = np.array([column_name + '_EUR' for column_name in header_numeric[column_dollars]])

In [446]:
header_numeric=np.concatenate((header_numeric,header_additional))

In [447]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [448]:
header_numeric[column_dollars]=[column_name + '_USD' for column_name in header_numeric[column_dollars]]

In [449]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [450]:
header_numeric=header_numeric[column_index_order]

In [451]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'funded_amnt_EUR', 'total_pymnt_USD', 'installment_EUR', 'exchange_rate'],
      dtype='<U19')

### Interest Rate

In [452]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'funded_amnt_EUR', 'total_pymnt_USD', 'installment_EUR', 'exchange_rate'],
      dtype='<U19')

In [453]:
loan_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [454]:
loan_data_numeric[:,5]=loan_data_numeric[:,5]/100

In [455]:
loan_data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

### Checkpoint 2: Numeric

In [458]:
checkpoint_numeric=checkpoint("Checkpoint-Numeric", header_numeric, loan_data_numeric)

In [459]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'funded_amnt_EUR', 'total_pymnt_USD', 'installment_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     1081.04,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,      848.86,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,      439.64,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1223.36,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,      318.78,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      283.49,        1.09]]))

## Creating the "Complete" Dataset

In [461]:
loan_data=np.hstack((checkpoint_numeric['data'], checkpoint_strings['data']))

In [462]:
header_full=np.concatenate((checkpoint_numeric['header'], checkpoint_strings['header']))

In [463]:
loan_data.shape

(10000, 17)

In [465]:
header_full.shape

(17,)

In [466]:
np.isnan(loan_data).sum()

0

## Sorting the New Dataset

In [467]:
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'funded_amnt_EUR', 'total_pymnt_USD', 'installment_EUR', 'exchange_rate',
       'issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [468]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [470]:
loan_data=loan_data[np.argsort(loan_data[:,0])]

In [471]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [472]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

## Storing the New Dataset

In [473]:
header_full.shape

(17,)

In [475]:
loan_data=np.vstack((header_full, loan_data))

In [477]:
loan_data.shape

(10001, 17)

In [480]:
np.savetxt("Loan-Data-Preprocessed.csv",
           loan_data,
           delimiter=',',
           fmt='%s')